languageCode = "en"
languageName = "English"
weight = 1
title = "Le Phu Duc"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/CoolKikyo.jpg"
  # secondaryLogo = "img/harrypotter.jpg"
  description = "Le Phu Duc's persional page"
  copyright = "Copyright Â© Le Phu Duc"

[author]
  name = "Jinn"
  image = "img/CoolKikyo.jpg"
  headline = "There are no hard challenges. We are hard"
  bio = "Anh thich Reverse Engineering boi vi anh thich ro e."
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
    { facebook = "https://facebook.com/lephuduc0309" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/lephuduc" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
    { reddit = "https://reddit.com/user/jinnlp" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = "https://t.me/lephuduc" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/lephuduck" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  #   { ko-fi = "https://ko-fi.com/username" },
  ]
